RWS/RWS/RWS/Controllers/PurchaseOrderController.cs
using RWS.DAL;
using RWS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RWS.Controllers
{
    public class PurchaseOrderController : Controller
    {
        //
        // GET: /PurchaseOrder/
        public ActionResult Index()
        {
            return View(Common.GetDataList<Order>(0));
        }

        //
        // GET: /PurchaseOrder/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /PurchaseOrder/Create
        public ActionResult Create()
        {
            Order ord = new Order();
            ord.OrderDate = DateTime.Now.Date;
            ord.Supplier = new SelectList(Common.GetDataList<Supplier>(0), "SupplierId", "DisplayName");
            ord.OrderDetail = Common.GetDataList<OrderDetail>(0);
            return View(ord);
        }

        //
        // POST: /PurchaseOrder/Create
        [HttpPost]
        public ActionResult Create(Order order)
        {
            try
            {
                Order.UpdateOrderHeader(order);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PurchaseOrder/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /PurchaseOrder/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PurchaseOrder/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /PurchaseOrder/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RWS/RWS/RWS/Controllers/SupplierController.cs
using RWS.DAL;
using RWS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RWS.Controllers
{
    public class SupplierController : Controller
    {
        //
        // GET: /Supplier/
        public ActionResult Index()
        {
            return View(Common.GetDataList<Supplier>(0));
        }

        //
        // GET: /Supplier/Details/5
        public ActionResult Details(int id)
        {
            return View(Common.GetDataList<Supplier>(id).FirstOrDefault());
        }

        //
        // GET: /Supplier/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Supplier/Create
        [HttpPost]
        public ActionResult Create(Supplier supplier)
        {
            try
            {
                Supplier.UpdateSupplier(supplier);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Supplier/Edit/5
        public ActionResult Edit(int id)
        {
            return View(Common.GetDataList<Supplier>(id).FirstOrDefault());
        }

        //
        // POST: /Supplier/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Supplier supplier)
        {
            try
            {
                Supplier.UpdateSupplier(supplier);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Supplier/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Supplier/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RWS/RWS/RWS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Liquor Shop Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Styles.Render("~/Content/jquery-ui.min.css")
    @Scripts.Render("~/Scripts/jquery-ui.min.js")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Liquor Shop Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Suppliers", "Index", "Supplier")</li>
                    <li>@Html.ActionLink("Empty Categories", "Index", "EmptyCategory")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Bank Accounts", "Index", "BankAccount")</li>
                    <li>@Html.ActionLink("Expenses", "Index", "ExpenseType")</li>
                    <li>@Html.ActionLink("Purchase Order", "Index", "PurchaseOrder")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Saranrajah</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>